#!/bin/sh
# Package the already installed rescue core on macOS. AI/Oil remain absent
# after the container resource stop. This is explicitly a partial candidate.
set -eu
cd "$(dirname "$0")/.."
check_space() { [ "$(df -Pk . | awk 'END {print $4}')" -ge "$1" ] || { echo 'Stop: inadequate host packaging headroom' >&2; exit 1; }; }
check_space 44040192  # 40 GiB reserve + 2 GiB bounded packaging allowance
cp build/rootfs/boot/config-*-lts build/evidence/kernel.config
# These are duplicate boot payloads generated by Alpine's install trigger.
# The ISO carries its own kernel and our Alpenglow rescue initramfs.
rm -f build/rootfs/boot/vmlinuz-lts build/rootfs/boot/initramfs-lts
mkdir -p build/iso-root/boot/limine
cp build/native/vmlinuz build/iso-root/boot/vmlinuz
(cd build/rootfs; find . -print0 | LC_ALL=C sort -z | /usr/bin/cpio -0 -o -H newc -R 0:0 2>../evidence/core-cpio.txt | zstd -6 -T2 -f -o ../initramfs.cpio.zst)
check_space 41943040
rm -f build/iso-root/boot/initramfs.cpio.zst
ln build/initramfs.cpio.zst build/iso-root/boot/initramfs.cpio.zst
cp build/limine/limine-bios.sys build/limine/limine-bios-cd.bin build/limine/limine-uefi-cd.bin build/iso-root/boot/limine/
cat > build/iso-root/boot/limine/limine.conf <<'EOF'
timeout: 0
verbose: no

/Alpenglow Rescue CORE DEVELOPMENT (AI/Oil absent)
  protocol: linux
  path: boot():/boot/vmlinuz
  cmdline: console=tty0 console=ttyS0 init=/init alpenglow.rescue=1
  module_path: boot():/boot/initramfs.cpio.zst
EOF
build/native-tools/installed/bin/xorriso -as mkisofs -o build/alpenglow-rescue-core-x86_64.iso -V ALPENGLOW_RESCUE -r -J \
  -b boot/limine/limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table \
  --efi-boot boot/limine/limine-uefi-cd.bin -efi-boot-part --efi-boot-image --protective-msdos-label build/iso-root
cc -O2 -o build/limine/limine build/limine/limine.c
build/limine/limine bios-install build/alpenglow-rescue-core-x86_64.iso
shasum -a 256 build/alpenglow-rescue-core-x86_64.iso build/initramfs.cpio.zst build/native/vmlinuz >build/evidence/core-SHA256SUMS
stat -f '%N %z' build/alpenglow-rescue-core-x86_64.iso build/initramfs.cpio.zst build/native/vmlinuz >build/evidence/core-artifact-bytes.txt
check_space 41943040
